### ISSUE TITLE
how to build this project

### ISSUE THREAD

**Issue by trolologuy** [wvdk/Life-Calendar#46]
Hello,
I really like the concept behind this project and i would like to try it out. 
Is a "fix" to #40 and #45 planned ? Or is the project still "paused" ?
Or at least a bit of context on how to build the app? (never built an app on macOS... yet)

**Comment by wvdk** [comment]
Unfortunately this project is still on "pause" due to a lack of time. I honestly don't remember the current state of the app but I know it's nowhere near feature complete. Probably not worth the time but if you want to try to build the project you can open the `Life Calendar.xcodeproj` in Xcode

Thanks for the interest though :) I still have hopes and dreams of finishing it
